import type { NextPage } from "next";
import Head from "next/head";
import * as React from "react";
import NewVersion from "./components/newVersion";
import OldVersion from "./components/oldVersion";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <OldVersion /> */}
      <NewVersion />
    </div>
  );
};

export default Home;
